name: DragonWings-plugin
version: '1.3'
main: me.minecraft.plugin.dragonWingsPlugin.DragonWingsPlugin
api-version: '1.21'
description: Ender Dragon will drop an Elytra when defeated
folia-supported: true